sonar.projectKey=event-tracker
sonar.working.directory=C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker
sonar.pullrequest.cache.basepath=C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker

A88A30C1-5614-4BF9-8273-93C7A4A96EA7.sonar.projectKey=event-tracker:A88A30C1-5614-4BF9-8273-93C7A4A96EA7
A88A30C1-5614-4BF9-8273-93C7A4A96EA7.sonar.projectName=event-tracker
A88A30C1-5614-4BF9-8273-93C7A4A96EA7.sonar.projectBaseDir=C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker
A88A30C1-5614-4BF9-8273-93C7A4A96EA7.sonar.sourceEncoding=utf-8
A88A30C1-5614-4BF9-8273-93C7A4A96EA7.sonar.tests=
A88A30C1-5614-4BF9-8273-93C7A4A96EA7.sonar.sources=\
"C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker\\AuditTrailAttribute.cs",\
"C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker\\EventLog.cs",\
"C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker\\EventTracker.cs",\
"C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker\\Program.cs",\
"C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker\\UserActions.cs",\
"C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker\\obj\\event-tracker.csproj.nuget.dgspec.json",\
"C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker\\obj\\project.assets.json",\
"C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker\\bin\\Debug\\net10.0\\event-tracker.deps.json",\
"C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker\\bin\\Debug\\net10.0\\event-tracker.runtimeconfig.json",\
"C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker\\obj\\Debug\\net10.0\\event-tracker.sourcelink.json"

A88A30C1-5614-4BF9-8273-93C7A4A96EA7.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker\\.sonarqube\\out\\0"
A88A30C1-5614-4BF9-8273-93C7A4A96EA7.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker\\.sonarqube\\out\\0\\Issues.json"
A88A30C1-5614-4BF9-8273-93C7A4A96EA7.sonar.cs.scanner.telemetry=\
"C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker\\.sonarqube\\out\\0\\Telemetry.json"

A88A30C1-5614-4BF9-8273-93C7A4A96EA7.sonar.working.directory=C:\\Users\\91905\\OneDrive\\Documents\\Desktop\\BridgeLabz-Training\\collections-c-sharp-practice\\scenario-based\\event-tracker\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=A88A30C1-5614-4BF9-8273-93C7A4A96EA7

